### PR TITLE
Updated

### PR DESCRIPTION
**Pull request by ankit-21**

### CODE REVIEW

**Comment by jjhbw** [comment]
Hi @ankit-21 , what is the intention of this PR?

We already have an `environment.yml` file from which people can easily derive a `requirements.txt` and I don't think we want to change the hardcoded setting to 'balanced'.

**Comment by ankit-21** [comment]
Hello Jurriaan

This PR was not intended for your repository and I apologise for the
confusion. I am working on my forked version and trying to train a model
based on your paper. Based on the data we have, I wanted to make changes to
my forked version when this happened and I somehow missed it.

That being said, I am super thankful to your team for doing this work and
making the code available on github. All the contents provided in the
repository are very comprehensive and indeed the .yml file does its work.

I would like to take this opportunity to ask a few questions about the
model: 1. Can you provide the case ID's of the final 395 TCGA cases you
used in training the attention model? I currently have access to the TCGA
dataset only, and wanted to train a naive model for this. 2. Can you please
tell me a little more about the 'random' and 'balanced' sampling technique
that is hardcoded in the train.py file?

I look forward to hearing from you.

Thanks
Ankit

**Comment by jjhbw** [comment]
@ankit-21 Makes sense, no problem at all!

We'd be very interested to hear what you are working on.

Note that the TCGA cases were not used to train the attention model, but only the self-supervised feature extraction model. We can look up the IDs for you if you want.

What do you want to know about the sampling technique? The 'balanced' setting is meant to reduce the impact of class imbalance, which was a concern for our classification task given our dataset. The paper explains this in more detail.

**Comment by ankit-21** [comment]
Thanks Jurriaan

In the current iteration, we are working on getting a basic naive model
with the data we have. For this we are planning to train the model with
just the TCGA dataset with 'imagenet' weights for feature extractor.

Having the IDs for the final shortlisted 395 cases that were used in
training the feature extractor would help in refining the dataset bit
further.

The sampling technique makes sense and I had to confirm what I was thinking
was correct. Just to confirm if I understand it correctly, for 'balanced'
setting, the model randomly picks slides of rare class multiple times in an
epoch, whereas for 'random' setting, the model randomly downsamples the
majority classes to match the number of cases in rare class (the setting
used in your case as explained in the paper), correct?

**Comment by jjhbw** [comment]
These are the TCGA IDs we used.
[TCGA_inclusion.csv](https://github.com/AIRMEC/im4MEC/files/10861868/TCGA_inclusion.csv)

For the exact implications of the sampling setting, I recommend reading the PyTorch documentation on the subject side-by-side with the code. That's the only way to ensure you understand this important parameter 100%.

**Comment by ankit-21** [comment]
Thanks a lot.
I really appreciate it.

**Pull request closed without merging**
